# Generated by Django 3.2.8 on 2021-12-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canopy',
            options={'verbose_name_plural': 'Canopies'},
        ),
        migrations.AlterField(
            model_name='diseaseimage',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.disease'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.plant'),
        ),
    ]
