# Generated by Django 3.2.8 on 2021-12-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211216_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseimage',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='canopy',
        ),
        migrations.RemoveField(
            model_name='plantimage',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='y_axis',
        ),
        migrations.DeleteModel(
            name='Canopy',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='DiseaseImage',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
