# Generated by Django 3.2.8 on 2021-12-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_capture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capture',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capture',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
